apiVersion: v1
kind: ConfigMap
data:
  strategy: |
    {
      "strategy":"SolverServiceV1",
      "params": {
        "policy": "dynamic",
        "mustInclude": [
          {
            "region":"northamerica"
          },
          {
            "region":"europe"
          }
        ],
        "minimumLocations": 2,
        "maximumLocations": 4,
        "minimumUsagePerLocation": 20
      }
    }
metadata:
  name: location-optimizer